---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - selfhealing.a2solutions.ca
  resources:
  - selfhealings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selfhealing.a2solutions.ca
  resources:
  - selfhealings/finalizers
  verbs:
  - update
- apiGroups:
  - selfhealing.a2solutions.ca
  resources:
  - selfhealings/status
  verbs:
  - get
  - patch
  - update
